# Alacritty Configuration
# Modern, fast terminal emulator configuration
# https://alacritty.org/config-alacritty.html

# General configuration
[general]
import = [
    "/Users/phaedrus/Development/alacritty-theme/themes/rose_pine.toml"
]

# Terminal emulation
[env]
TERM = "xterm-256color"

# Window configuration
[window]
# Window dimensions (changes require restart)
dimensions = { columns = 120, lines = 30 }

# Window position (changes require restart)
# position = { x = 0, y = 0 }

# Window padding (changes require restart)
padding = { x = 8, y = 8 }

# Spread additional padding evenly around the terminal content
dynamic_padding = true

# Window decorations
# Values for `decorations`:
#   - full: Borders and title bar
#   - none: Neither borders nor title bar
decorations = "full"

# Background opacity
opacity = 0.95

# Startup Mode (changes require restart)
# Values for `startup_mode`:
#   - Windowed
#   - Maximized
#   - Fullscreen
startup_mode = "Windowed"

# Window title
title = "Alacritty"

# Allow terminal applications to change Alacritty's window title
dynamic_title = true

# Window class (Linux/BSD only)
class = { instance = "Alacritty", general = "Alacritty" }

# Decorations theme variant
decorations_theme_variant = "Dark"

# Resize increments
resize_increments = true

# Option as Alt (macOS only)
option_as_alt = "OnlyLeft"

# Scrolling
[scrolling]
# Maximum number of lines in the scrollback buffer
history = 10000

# Scrolling distance multiplier
multiplier = 3

# Font configuration
[font]
# Normal (roman) font face
normal = { family = "FiraCode Nerd Font Mono", style = "Regular" }

# Bold font face
bold = { family = "FiraCode Nerd Font Mono", style = "Bold" }

# Italic font face
italic = { family = "FiraCode Nerd Font Mono", style = "Regular" }

# Bold italic font face
bold_italic = { family = "FiraCode Nerd Font Mono", style = "Bold" }

# Point size
size = 14.0

# Offset is the extra space around each character
offset = { x = 0, y = 0 }

# Glyph offset determines the locations of the glyphs within their cells
glyph_offset = { x = 0, y = 0 }

# Use built-in font for box drawing characters
builtin_box_drawing = true

# Bell
[bell]
animation = "EaseOutExpo"
duration = 100
color = "#e0af68"
command = "None"

# Selection
[selection]
# This string contains all characters that are used as separators for "semantic words" in Alacritty
semantic_escape_chars = ",│`|:\"' ()[]{}<>\t"

# When set to `true`, selected text will be copied to the primary clipboard
save_to_clipboard = true

# Cursor
[cursor]
# Cursor style
style = { shape = "Block", blinking = "Off" }

# Vi mode cursor style
vi_mode_style = "None"

# Cursor blinking interval in milliseconds
blink_interval = 750

# Time after which cursor stops blinking, in seconds
blink_timeout = 5

# If this is `true`, the cursor will be rendered as a hollow box when the window is not focused
unfocused_hollow = true

# Thickness of the cursor relative to the cell width as floating point number from `0.0` to `1.0`
thickness = 0.15

# Terminal
[terminal]
# Controls the OSC 52 behavior for clipboard interactions
osc52 = "OnlyCopy"

# Mouse
[mouse]
# If this is `true`, the cursor is temporarily hidden when typing
hide_when_typing = true

# Key bindings
[[keyboard.bindings]]
key = "V"
mods = "Command"
action = "Paste"

[[keyboard.bindings]]
key = "C"
mods = "Command"
action = "Copy"

[[keyboard.bindings]]
key = "Q"
mods = "Command"
action = "Quit"

[[keyboard.bindings]]
key = "W"
mods = "Command"
action = "Quit"

[[keyboard.bindings]]
key = "N"
mods = "Command"
action = "SpawnNewInstance"

[[keyboard.bindings]]
key = "Return"
mods = "Command"
action = "ToggleFullscreen"

[[keyboard.bindings]]
key = "Plus"
mods = "Command"
action = "IncreaseFontSize"

[[keyboard.bindings]]
key = "Minus"
mods = "Command"
action = "DecreaseFontSize"

[[keyboard.bindings]]
key = "Key0"
mods = "Command"
action = "ResetFontSize"

[[keyboard.bindings]]
key = "K"
mods = "Command"
action = "ClearHistory"

[[keyboard.bindings]]
key = "K"
mods = "Command"
chars = "\u000C"

# Tmux-style key bindings
[[keyboard.bindings]]
key = "T"
mods = "Command"
chars = "\u0002c"  # Ctrl-b c (new tmux window)

[[keyboard.bindings]]
key = "D"
mods = "Command|Shift"
chars = "\u0002\""  # Ctrl-b " (split horizontal)

[[keyboard.bindings]]
key = "D"
mods = "Command"
chars = "\u0002%"  # Ctrl-b % (split vertical)

# Window navigation with Command+arrow
[[keyboard.bindings]]
key = "Left"
mods = "Command"
chars = "\u0002h"  # Ctrl-b h

[[keyboard.bindings]]
key = "Right"
mods = "Command"
chars = "\u0002l"  # Ctrl-b l

[[keyboard.bindings]]
key = "Up"
mods = "Command"
chars = "\u0002k"  # Ctrl-b k

[[keyboard.bindings]]
key = "Down"
mods = "Command"
chars = "\u0002j"  # Ctrl-b j

# Debug
[debug]
# Display the time it takes to redraw each frame
render_timer = false

# Keep the log file after quitting Alacritty
persistent_logging = false

# Log level
log_level = "Warn"

# Print all received window events
print_events = false

# Highlight window damage information
highlight_damage = false